# Generated by Django 3.2.18 on 2023-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('email_msm', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Import_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='my_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutform',
            name='html_img',
        ),
    ]
