# Generated by Django 3.2.18 on 2023-05-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0002_auto_20230512_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_notice',
            name='image',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
