# Generated by Django 3.2.18 on 2023-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0003_alter_import_notice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_gallery', models.ImageField(upload_to='gallery_img')),
            ],
        ),
        migrations.CreateModel(
            name='Team_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_team', models.ImageField(upload_to='team_img')),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
