# Generated by Django 3.2.18 on 2023-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0004_gallery_img_team_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_team', models.ImageField(upload_to='team_img')),
                ('year', models.CharField(max_length=20)),
                ('insta_link', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Team_img',
        ),
    ]
