# Generated by Django 3.2.18 on 2023-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0006_team_info_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='std_post',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
