# Generated by Django 3.2.18 on 2023-05-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0009_auto_20230512_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
