# Generated by Django 3.2.18 on 2023-05-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_college', '0010_auto_20230513_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_info',
            name='std_post',
            field=models.CharField(max_length=30),
        ),
    ]
