# Generated by Django 3.2.20 on 2023-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBranch',
            fields=[
                ('branch_name', models.CharField(max_length=30)),
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='branch_images')),
            ],
        ),
        migrations.CreateModel(
            name='pyq',
            fields=[
                ('branch_name', models.CharField(max_length=30)),
                ('pyq_id', models.AutoField(primary_key=True, serialize=False)),
                ('pyq_details', models.CharField(max_length=300)),
                ('pyq_image', models.ImageField(upload_to='pyq_images')),
            ],
        ),
    ]
