# Generated by Django 3.2.20 on 2023-08-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyq',
            old_name='pyq_image',
            new_name='pyq_Image',
        ),
    ]
