# Generated by Django 3.2.20 on 2023-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0002_rename_pyq_image_pyq_pyq_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
