# Generated by Django 3.2.20 on 2023-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0003_pyq_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='pyq_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pyq',
            name='student_year',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
