# Generated by Django 3.2.20 on 2023-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0004_auto_20230823_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='new_year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
