# Generated by Django 3.2.20 on 2023-08-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0005_pyq_new_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyq',
            name='new_year',
        ),
    ]
