# Generated by Django 3.2.20 on 2023-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0006_remove_pyq_new_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_formate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('student_year', models.CharField(max_length=1)),
                ('pyq_pdf', models.ImageField(upload_to='pyq_pdfs')),
            ],
        ),
    ]
