# Generated by Django 3.2.20 on 2023-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorces_app', '0007_pdf_formate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_formate',
            name='pyq_pdf',
            field=models.FileField(upload_to='pyq_pdfs'),
        ),
    ]
